### ISSUE TITLE
Rectangle is used accidentally

### ISSUE THREAD

**Issue by mcoblenz** [whitneylarose/JHotDraw5.3#2]
By calling the class Rectangle, it is automatically used in places that import contrib.*. We need to rename Rectangle to avoid this problem (perhaps to ImmutableRectangle?).

**Comment by whitneylarose** [comment]
The name of file was changed to ImmutableRectangle in order to avoid being used in places that import contrib.*.
https://github.com/whitneylarose/JHotDraw5.3/issues/2
